export const menuData = [
    {
        key:'item1',
        title:'前沿/区域块链/人工智能'
    },{
        key:'item2',
        title:'前端/小程序/JS'
    },{
        key:'item3',
        title:'前端/小程序/JS'
    },{
        key:'item4',
        title:'前端/小程序/JS'
    },{
        key:'item5',
        title:'前端/小程序/JS'
    },{
        key:'item6',
        title:'前端/小程序/JS'
    }
];